### ISSUE TITLE
‘intro’ text on the homepage will not update

### ISSUE THREAD

**Issue by jobarratt** [okfn/ckanext-salford#14]
https://salforddataquay.uk/ckan-admin/config
I have also tested this and it seems to not be working.

**Comment by amercader** [comment]
It's hardcoded in the extension template, should be straight-forward to fix https://github.com/okfn/ckanext-salford/blob/master/ckanext/salford/templates/home/index.html#L16

**Comment by jobarratt** [comment]
text below

"Welcome to the Salford DATA QUAY: Unlocking the potential of the City's Open Data."

"The Salford DATA QUAY brings Salford data together in one place from public, private and voluntary organisations. This data is freely accessible to all to use and re-use, (as per the licensing conditions). Making our data 'open' in this way provides an opportunity for us to work smarter to better inform and transform Salford's future."

**Comment by jobarratt** [comment]
Just need a 'yes' or 'no' to the below. Thanks Adria.

"Just a question on that: I can understand the org and groups text having to be coded – but is there a reason that the intro text has to be hardcoded – as I’m presuming that any updates will now need to be a development job rather than config via the GUI? Hopefully we won’t need to change it but…is there any way that it could be updatable via the GUI as the other homepage texts."

**Comment by amercader** [comment]
Text updated: https://salforddataquay.uk/

They can update it via the config page https://salforddataquay.uk/ckan-admin/config
Up until now it wasn't possible because of a bug in the templates, as I mentioned earlier.

**Comment by jobarratt** [comment]
What they ideally want is for the "Welcome to the Salford DATA QUAY: Unlocking the potential of the City's Open Data" to appear on one line. But be formatted as a title (with the pink line separating this form the copy). It is fine that is not editable. 

If this is not possible, can we revert to how it was this morning. 

![screen shot 2015-03-26 at 13 30 22](https://cloud.githubusercontent.com/assets/8183744/6850959/179c5d2e-d3d4-11e4-9769-ed6b1d6b32ec.png)

**Comment by jobarratt** [comment]
Title can change to "Unlocking the potential of the City's Open Data"
