### ISSUE TITLE
Metadata for spatial sources is not displaying

### ISSUE THREAD

**Issue by jobarratt** [okfn/ckanext-salford#15]
on the Data Quay -we don’t seem able to view the metadata for any sources, (spatial) that are harvested from DGU.

It seems that there is simply a url to the data resource and supporting text  - but none of the metadata that we supports it, (especially licensing – which is key to usablity of the site).

**Comment by amercader** [comment]
Not sure I understand, can you provide a link to an example dataset?

> (spatial) that are harvested from DGU

Remember, nothing is harvested _from_ DGU #12

**Comment by jobarratt** [comment]
"Apologies – I meant the metadata that is harvested from Metadata Editor (Uk) – for spatial data.

For example when we view a dataset at DGU we get the following metadata:
![screen shot 2015-03-26 at 11 20 26](https://cloud.githubusercontent.com/assets/8183744/6845239/3dfd220c-d3aa-11e4-837a-d8a93cc7c421.png)

Compared with (below) at the Salford DataQuay site for the same dataset:
![screen shot 2015-03-26 at 11 20 13](https://cloud.githubusercontent.com/assets/8183744/6845230/2ca20a54-d3aa-11e4-80f7-56b0b6d69d4c.png)

I am concerned that the metadata for the dataset can be as important as the dataset itself in promoting it’s value for use and re-usability; and in not displaying this at the Dataquay level – we are providing only half the picture. We might not need all the metadata that is held at DGU but I would suggest that there will be some that we would want to map to our own metadata schema, (which I am in the process of finalising –with the intention of manually adding as ‘custom fields,’ as advised).

Also for those datasets that have been harvested from UKME – I am still unsure as to:

·         Why it doesn’t seem to be associated to a license type (tagging with appropriate license is again required to promote appropriate re-use) – there is no indicator on DataQuay of the license type this has been attributed with at UKME (and which is visible at DGU)."

**Comment by amercader** [comment]
- Metadata fields not showing up: the metadata fields are there, created by the harvester, only not displayed on the frontend (see `extras` in this [API call](https://salforddataquay.uk/api/action/package_show?id=local-landscape-character-assessment-areas)). We can display some of them, but not all. "Added to DGU", "Theme", "Themes (secondary)" are computed on DGU.
- License type not displayed: the harvesting on DGU must be using some logic to decide which license to use. I can see if I can port it to the Salford site but it might be a bit tricky.

**Comment by amercader** [comment]
I've added some extra metadata fields in the dataset page, the rest are not easy or impossible to add:

https://salforddataquay.uk/dataset/local-landscape-character-assessment-areas

I didn't have time to look at the licence issue properly

**Comment by amercader** [comment]
@jobarratt, license situation:

For spatial records, the license information is coming from the `accessConstraints` field in the original GEMINI2 XML document. This is a free text field, with values like:

```
Public Sector End User Licence - INSPIRE (http://www.ordnancesurvey.co.uk/business-and-government/public-sector/mapping-agreements/inspire-licence.html)
```

In order for this to be translated to a proper license field in CKAN, it needs some processing to extract the License name and url and match against the standard license list and codes in CKAN. This should be done at the harvester extension point [1]. For now, the whole contents of the field are displayed in the Additional Metadata section of the dataset page (if the field if present). The license section on the left hand column won't come up and the datasets won't be able to filtered by license on the search page.

[1] https://github.com/okfn/ckanext-salford/blob/c35a6c2487f53f347f8a3dc4bd09b69c896b8c7a/ckanext/salford/plugin.py#L132

**Comment by jobarratt** [comment]
Just an observation/query re the metadata.

Looking at metadata for datasets that are harvested from UKME to DGU – it’s possible to view ‘themes, in the metadata. ’  As far as I am aware this is DGU specific metadata, (we don’t add it at UKME)  so I’m just wondering how this particular metadata is created/added by DGU – and is it something that we could perhaps replicate to attach SCC metadata to those INSPIRE datasets that we can’t edit.

![screen shot 2015-03-27 at 15 45 10](https://cloud.githubusercontent.com/assets/8183744/6871126/6dbca172-d498-11e4-86ab-b98ef2b5cf10.png)

**Comment by amercader** [comment]
The theme field is created (or guessed rather) in DGU depending on the values of other fields in the metadata.

The actual logic can be found here, and it does not seem like it would be easy to port to the Salford site:

https://github.com/datagovuk/ckanext-dgu/blob/master/ckanext/dgu/lib/theme.py#L143
