### ISSUE TITLE
Can the text on the left-hand-side on the 'groups,’ and ‘organisation pages be edited?

### ISSUE THREAD

**Issue by jobarratt** [okfn/ckanext-salford#16]
Is it possible to change the explanatory text on the left-hand-side on the  'groups,’ and ‘organisation,’ pages?

**Comment by amercader** [comment]
Yes, but it needs to be overriden on the extension templates (ie if they provide it, we'll update it)

**Comment by jobarratt** [comment]
They will send the text later today. 
Just need a 'yes' or 'no' to the below. Thanks Adria.

"Just  a question on that: I can understand the org and groups text having to be coded – but is there a reason that the intro text has to be hardcoded – as I’m presuming that any updates will now need to be a development job rather than config via the GUI?  Hopefully we won’t need to change it but…is there any way that it could be updatable via the GUI as the other homepage texts."

**Comment by jobarratt** [comment]
Organisations:
Each dataset will belong to an organisation who is responsible for managing it.  Members of these organisations can request to become authorised users with the ability to add, edit and/or publish datasets on the organisations behalf.

Groups:
' Groups' are a way of organising datasets into topics  as a simple way of helping people to find similar/related datasets. Datasets can be assigned to more than one group where the data relates to multiple topics.  Users can either browse by 'group,' or refine search results by 'group'.

**Comment by amercader** [comment]
Done

https://salforddataquay.uk/organization
https://salforddataquay.uk/group
