### ISSUE TITLE
Harvesting inconsistencies

### ISSUE THREAD

**Issue by jobarratt** [okfn/ckanext-salford#17]
Can you confirm that you have not brought any of the data that was on DataGM over to the Dataquay, (and just populated data quay with data from DGU and then pushed from Data quay to Data GM) – as we are trying to account for inconsistencies with number of datasets at different sites:

43 datasets on SCC Dataquay (13 are OGL – the remaining 28 have no licensing tag – but presume this is the 28 INSPIRE datasets from DGU -below)

42 datasets on DGU (only 28 are INSPIRE)

68 datasets on Data GM

http://datagm.org.uk/dataset/salford-data-quay (42 harvested from SDQ)

**Comment by amercader** [comment]
All datasets currently on the site come from either:
- DGU (non-spatial ones): 13
- The own Salford WAF sources (spatial ones): 28 - These are the same sources that are harvested into DGU

( See #12)

I have not harvested to and from DataGM. I'd suggest clearing all datasets on DataGM and reharvesting from SCC Dataquay to get the up to date ones on the DataGM site.

**Comment by amercader** [comment]
Anything else needed here?
