### ISSUE TITLE
LA function and service question

### ISSUE THREAD

**Issue by jobarratt** [okfn/ckanext-salford#20]
I know you’re cracking on with the DGU metadata synchronisation but have noticed another issue – if you could look at when you get a chance.

Have just been trying to add metadata and am struggling with the LA function list.

It is difficult to choose something relevant when there is no visible list of options. I think that only  the top two levels of the hierarchy of terms have been used – which is fine – but this would be better as a drop down list like the, ‘info class,’ (pub scheme) rather than auto-complete text.

I think for LA Services – because there are so many –auto complete text is acceptable. (Are you able to confirm if the LA service list was used or whether All service list was used). If it was LA service – it would be useful to know how easy it would be to change at a later date to All Service).

**Comment by amercader** [comment]
Yes, we could make the functions field a dropdown. It would take a couple of hours work more or less.

For services we actually used the "All Services" list. I guess we should use the "LA functions" one. It should be easy to change the underlying list, but it would be good to spend about 1-2 hour to sort it out properly and make which list do you use configurable.
