### ISSUE TITLE
Fix twitter feed on homepage

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-salford#8]
Looks like the actual library that does the parsing is not loaded

**Comment by amercader** [comment]
cc @mintcanary

**Comment by smth** [comment]
Indeed. This is what I said to @jobarratt See step 5 (Bower components) of readme https://github.com/okfn/ckanext-salford/blob/master/README.rst

**Comment by amercader** [comment]
Building bower is not enough. you still need to link to built libraries somewhere, eg in the resource.config file or directly in the template

**Comment by smth** [comment]
It must have been linked somewhere, my local version works..

Edit: https://github.com/okfn/ckanext-salford/blob/master/ckanext/salford/templates/base.html#L11
