### ISSUE TITLE
Americanisation

### ISSUE THREAD

**Issue by jobarratt** [okfn/ckanext-salford#9]
There are still parts of text that are Americanised, - ‘organization,’ etc

From Adria - These need to be updated on the en_GB translation file and recompiled. Ideally we would do that before the release day so we can use the core translation, but if not we can use a local translation file. Shouldn’t take more than an hour to fix the missing strings (would be good to have a full list)

**Comment by amercader** [comment]
This is done and deployed https://salforddataquay.uk/organization
